<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lumispring.framework</groupId>
        <artifactId>framework-boot</artifactId>
        <version>3.4.0.0</version>
    </parent>

    <packaging>pom</packaging>

    <artifactId>framework-starter</artifactId>

    <modules>
        <module>framework-starter-parent</module>
        <module>framework-starter-web</module>
        <module>framework-starter-base</module>
        <module>framework-starter-database</module>
        <module>framework-starter-security</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>